### ISSUE TITLE
Possibility to manage Chat-GPT Plus

### ISSUE THREAD

**Issue by arnogues** [VaibhavAcharya/code-gpt#5]
Is it possible to have to possibility to connect with our account to use Chat GPT Plus for those who paid

**Comment by Stoffberg** [comment]
The library is currently using GPT3-Davinci model, since ChatGPT doesn't have an official API this is hard to do, although not impossible. You can run a multi-account network to scrape the data out of ChatGPT with something like Puppeteer, but @VaibhavAcharya needs to do quite a lot of work on the backend to make that a reality.

**Comment by VaibhavAcharya** [comment]
That would be just too much work for this little project. 😅

**Comment by arnogues** [comment]
Sorry.
I close this issue
